[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "osr-tracking-tool-production.up.railway.app"

[context.deploy-preview.environment]
  VITE_BACKEND_URL = "osr-tracking-tool-production.up.railway.app"

