# backend/railway.toml

[build]
builder   = "nixpacks"
providers = ["python"]     # detect Python apps

[deploy]
healthcheckPath         = "/api/health"
healthcheckTimeout      = 300
restartPolicyType       = "on_failure"
restartPolicyMaxRetries = 5

[nixpacks]
python_version = "3.11"
# bring pip, setuptools & wheel into the store so the auto-pipeline venv steps won't fail
packages = [
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[variables]
FLASK_ENV        = "production"
FLASK_DEBUG      = "false"
SECRET_KEY       = "change-this-in-production-environment"
PYTHONUNBUFFERED = "1"

